CREATE OR REPLACE PROCEDURE SP_DATVE(
    MANV IN NVARCHAR2,
    MATV IN NVARCHAR2,
    MASC IN NVARCHAR2,
    MAGHE IN NVARCHAR2,
    TONGTIEN IN NUMBER,
    MAKM IN NVARCHAR2,
    SOHD OUT NVARCHAR2
)
AS
    RCNT_DATVE NUMBER;
    RCNT_SUATCHIEU NUMBER;
    RCNT_GHE NUMBER;
    SOHD_INSERTED NUMBER;
BEGIN
    SELECT COUNT(*)
    INTO RCNT_SUATCHIEU
    FROM SUATCHIEU SC
    WHERE SC.MASC = MASC;
    
    IF RCNT_SUATCHIEU = 0
    THEN
        RAISE_APPLICATION_ERROR(-20001, 'Khong co suat chieu ' || MASC);
    END IF;
    
    SELECT COUNT(*)
    INTO RCNT_GHE
    FROM GHE G
    WHERE G.MAGHE = MAGHE;
    
    IF RCNT_GHE = 0
    THEN
        RAISE_APPLICATION_ERROR(-20001, 'Khong co ghe ' || MAGHE);
    END IF;

    SELECT COUNT(*)
    INTO RCNT_DATVE
    FROM DATVE DV
    WHERE DV.MASC = MASC AND DV.MAGHE = MAGHE;
    
    IF RCNT_DATVE = 0
    THEN
        INSERT INTO HOADON(MANV, MATV, NGAYHD, TONGTIEN) 
        VALUES (MANV, MATV, to_date(SYSDATE,'dd-mm-YYYY'), TONGTIEN)
        RETURNING SOHD
        INTO SOHD_INSERTED;
        
        SOHD := SOHD_INSERTED;
        
        INSERT INTO DATVE(MAGHE, MASC, SOHD, MAKM, THANHTIEN)
        VALUES (MAGHE, MASC, SOHD_INSERTED, MAKM, TONGTIEN);
    ELSE
        RAISE_APPLICATION_ERROR(-20003, 'Ghe da duoc dat');
    END IF;
END;

--DECLARE
--    SOHD NUMBER;
--BEGIN
--    SP_DATVE(1, 1, 1, 1, 100, NULL, SOHD);
--    DBMS_OUTPUT.PUT_LINE(SOHD);
--END; 