create or replace PROCEDURE SP_DATVE(
    p_MANV IN NVARCHAR2,
    p_MATV IN NVARCHAR2,
    p_MASC IN NVARCHAR2,
    p_MAGHE IN NVARCHAR2,
    p_TONGTIEN IN NUMBER,
    p_MAKM IN NVARCHAR2
)
AS
    RCNT_DATVE NUMBER;
    RCNT_SUATCHIEU NUMBER;
    RCNT_GHE NUMBER;
    SOHD_INSERTED NUMBER;
    CURSOR CUR IS SELECT DATVE.MAGHE FROM DATVE WHERE DATVE.MASC = p_MASC;
    V_MAGHE DATVE.MAGHE%TYPE;
    BOOL_GHEDADAT NUMBER :=0;
BEGIN
    SELECT COUNT(*)
    INTO RCNT_SUATCHIEU
    FROM SUATCHIEU SC
    WHERE SC.MASC = p_MASC;

    IF RCNT_SUATCHIEU = 0
    THEN
        RAISE_APPLICATION_ERROR(-20001, 'Khong co suat chieu ' || p_MASC);
    END IF;

    SELECT COUNT(*)
    INTO RCNT_GHE
    FROM GHE G
    WHERE G.MAGHE = p_MAGHE;

    IF RCNT_GHE = 0
    THEN
        RAISE_APPLICATION_ERROR(-20001, 'Khong co ghe ' || p_MAGHE);
    END IF;

    OPEN CUR;
    LOOP
            FETCH CUR INTO V_MAGHE;
            EXIT WHEN CUR%NOTFOUND;
            IF V_MAGHE = p_MAGHE
                THEN BOOL_GHEDADAT:=1;
            END IF;
    END LOOP;
    CLOSE CUR;
    IF BOOL_GHEDADAT = 0
    THEN
        INSERT INTO HOADON(MANV, MATV, NGAYHD, TONGTIEN) 
        VALUES (p_MANV, p_MATV, to_date(SYSDATE,'dd-mm-YYYY'), p_TONGTIEN)
        RETURNING SOHD
        INTO SOHD_INSERTED;
        
        INSERT INTO DATVE(MAGHE, MASC, SOHD, MAKM, THANHTIEN)
        VALUES (p_MAGHE, p_MASC, SOHD_INSERTED, p_MAKM, p_TONGTIEN);
    ELSE
        RAISE_APPLICATION_ERROR(-20003, 'Ghe da duoc dat');
    END IF;
END;