--FUNCTION KI?M TRA GH?
create or replace function F_CHECK_SEAT(
P_MAGHE in nvarchar2,
P_MASC IN NVARCHAR2)
RETURN NUMBER
IS
    CURSOR CUR IS SELECT DATVE.MAGHE FROM DATVE WHERE DATVE.MASC = p_MASC;
    V_MAGHE DATVE.MAGHE%TYPE;
    BOOL_GHEDADAT NUMBER :=0;
BEGIN
    OPEN CUR;
    LOOP
            FETCH CUR INTO V_MAGHE;
            EXIT WHEN CUR%NOTFOUND;
            IF V_MAGHE = p_MAGHE
                THEN BOOL_GHEDADAT:=1;
            END IF;
    END LOOP;
    CLOSE CUR;
    IF BOOL_GHEDADAT = 1
    THEN
        RAISE_APPLICATION_ERROR(-20003, 'Ghe da duoc dat');
    END IF;
    RETURN BOOL_GHEDADAT;
END;
--FUNCTION T?O HÓA ??N
create or replace function F_CREATE_HOADON_DATVE(
P_MANV in nvarchar2,
P_MATV in nvarchar2,
P_MAKM IN NVARCHAR2,
P_THANHTIEN in NUMBER
)
return NUMBER
IS
    V_SYSDATE DATE := to_date(SYSDATE,'dd-mm-YYYY');
    V_SOHD HOADON.SOHD%TYPE;
BEGIN
        INSERT INTO HOADON(MANV, MATV, NGAYHD, TONGTIEN, MAKM) 
            VALUES (p_MANV, p_MATV, V_SYSDATE, p_THANHTIEN,P_MAKM)
                RETURNING SOHD INTO V_SOHD;
    RETURN V_SOHD;
END;
--PROCEDURE ??T VÉ
CREATE OR REPLACE PROCEDURE SP_DATVE(
P_MAGHE IN NVARCHAR2,
P_MASC IN NVARCHAR2,
P_SOHD IN NUMBER)
IS
BEGIN
    INSERT INTO DATVE VALUES(P_MAGHE, P_MASC, P_SOHD);
END;