/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Controller.Oracle;
import Controller.TaiKhoan_ctrl;
import java.awt.Color;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;


/**
 *
 * @author Phon
 */
public class DangNhap extends javax.swing.JFrame {

    /**
     * Creates new form DangNhap
     */
    public DangNhap() {
        initComponents();
        this.setLocationRelativeTo(null);//hiển thị giữa màn hình
        this.setTitle("Đăng nhập");
        this.setDefaultCloseOperation(EXIT_ON_CLOSE);//thoát chương trình khi bấm exit
        this.setVisible(true);//chạy chương trình
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        label_unive = new javax.swing.JLabel();
        label_pass = new javax.swing.JLabel();
        label_username = new javax.swing.JLabel();
        txt_username = new javax.swing.JTextField();
        txt_pass = new javax.swing.JPasswordField();
        button_login = new javax.swing.JButton();
        button_cancel = new javax.swing.JButton();
        label_unive1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setLayout(null);

        label_unive.setFont(new java.awt.Font("Corbel Light", 0, 24)); // NOI18N
        label_unive.setForeground(new java.awt.Color(255, 255, 255));
        label_unive.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_unive.setText("Welcome to Universal cinemas");
        jPanel1.add(label_unive);
        label_unive.setBounds(50, 70, 340, 50);

        label_pass.setFont(new java.awt.Font("Corbel Light", 0, 18)); // NOI18N
        label_pass.setForeground(new java.awt.Color(255, 255, 255));
        label_pass.setText("Password: ");
        jPanel1.add(label_pass);
        label_pass.setBounds(20, 220, 80, 40);

        label_username.setFont(new java.awt.Font("Corbel Light", 0, 18)); // NOI18N
        label_username.setForeground(new java.awt.Color(255, 255, 255));
        label_username.setText("Username:");
        jPanel1.add(label_username);
        label_username.setBounds(20, 160, 100, 40);

        txt_username.setBackground(new java.awt.Color(0, 0, 0));
        txt_username.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txt_username.setForeground(new java.awt.Color(255, 255, 255));
        txt_username.setText("username");
        txt_username.setCaretColor(new java.awt.Color(255, 255, 255));
        txt_username.setOpaque(false);
        txt_username.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_usernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_usernameFocusLost(evt);
            }
        });
        txt_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_usernameActionPerformed(evt);
            }
        });
        jPanel1.add(txt_username);
        txt_username.setBounds(130, 160, 230, 30);

        txt_pass.setBackground(new java.awt.Color(0, 0, 0));
        txt_pass.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txt_pass.setForeground(new java.awt.Color(255, 255, 255));
        txt_pass.setText("password");
        txt_pass.setCaretColor(new java.awt.Color(255, 255, 255));
        txt_pass.setOpaque(false);
        txt_pass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_passFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_passFocusLost(evt);
            }
        });
        txt_pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_passActionPerformed(evt);
            }
        });
        jPanel1.add(txt_pass);
        txt_pass.setBounds(130, 230, 230, 30);

        button_login.setBackground(new java.awt.Color(52, 152, 219));
        button_login.setFont(new java.awt.Font("Corbel Light", 1, 14)); // NOI18N
        button_login.setForeground(new java.awt.Color(255, 255, 255));
        button_login.setText("Sign in");
        button_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_loginActionPerformed(evt);
            }
        });
        jPanel1.add(button_login);
        button_login.setBounds(120, 310, 90, 40);

        button_cancel.setBackground(new java.awt.Color(52, 152, 219));
        button_cancel.setFont(new java.awt.Font("Corbel Light", 1, 14)); // NOI18N
        button_cancel.setForeground(new java.awt.Color(255, 255, 255));
        button_cancel.setText("Cancel");
        button_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_cancelActionPerformed(evt);
            }
        });
        jPanel1.add(button_cancel);
        button_cancel.setBounds(260, 310, 90, 40);

        label_unive1.setFont(new java.awt.Font("Calibri Light", 0, 36)); // NOI18N
        label_unive1.setForeground(new java.awt.Color(255, 255, 255));
        label_unive1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_unive1.setText("Sign in");
        jPanel1.add(label_unive1);
        label_unive1.setBounds(90, 30, 260, 60);

        jLabel1.setFont(new java.awt.Font("Corbel Light", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("__________________________________");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 420, 440, 16);

        jLabel2.setFont(new java.awt.Font("Corbel Light", 3, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("@gm.uit.edu.vn");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(180, 440, 120, 18);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 434, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_loginActionPerformed

        String username = txt_username.getText();
        String password = String.valueOf(txt_pass.getPassword());
        TaiKhoan_ctrl tkc = new TaiKhoan_ctrl();
        try {
            if(tkc.Login(username, password))
            {
                MaNV=tkc.getThongTinDangNhap(username);
                //hiển thị frame trang chủ
                Home trangchu = new Home();
                //Đóng đăng nhập
                this.dispose();
                Oracle.getConnection().close();
            }
            else
            {
             // hiển thị lỗi
                JOptionPane.showMessageDialog(null,"Invalid Username/ Password","Login error",2);
                Oracle.getConnection().close();
            }
            
            
        } catch (SQLException ex) {
            Logger.getLogger(DangNhap.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
        
    }//GEN-LAST:event_button_loginActionPerformed

    private void txt_usernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_usernameFocusGained
        //clear username khi click chuột
        if(txt_username.getText().trim().toLowerCase().equals("username"))
        {
            txt_username.setText("");
            txt_username.setForeground(Color.white);
        }
          
        
    }//GEN-LAST:event_txt_usernameFocusGained

    private void txt_passFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_passFocusLost
         String pass = String.valueOf(txt_pass.getPassword());
          if(pass.trim().equals("")||
           pass.trim().toLowerCase().equals("password"))
        {
            txt_pass.setText("password");
            txt_pass.setForeground(Color.PINK);
        }
    }//GEN-LAST:event_txt_passFocusLost

    private void button_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_cancelActionPerformed
        System.exit(0);
    }//GEN-LAST:event_button_cancelActionPerformed

    private void txt_passFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_passFocusGained
        //clear password khi click chuột vào password
        String pass = String.valueOf(txt_pass.getPassword());
        
        if(pass.trim().toLowerCase().equals("password"))
        {
            txt_pass.setText("");
            txt_pass.setForeground(Color.white);
        }
        
    }//GEN-LAST:event_txt_passFocusGained

    private void txt_usernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_usernameFocusLost
       //hiển thị "username" khi click trường khác
        if(txt_username.getText().trim().equals("")||
           txt_username.getText().trim().toLowerCase().equals("username"))
        {
            txt_username.setText("username");
            txt_username.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_txt_usernameFocusLost

    private void txt_passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_passActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_passActionPerformed

    private void txt_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_usernameActionPerformed

    /**
     * @param args the command line arguments
     */
     public static void main(String args[]) {
        
            
                DangNhap dangnhap = new DangNhap();
            
       
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_cancel;
    private javax.swing.JButton button_login;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel label_pass;
    private javax.swing.JLabel label_unive;
    private javax.swing.JLabel label_unive1;
    private javax.swing.JLabel label_username;
    private javax.swing.JPasswordField txt_pass;
    private javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables
    public static String MaNV;
    
}
