/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Controller.SuatChieu_ctrl;
import java.awt.Color;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;

/**
 *
 * @author Phon
 */
public class DatVe extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public DatVe() {
        initComponents();
        this.setLocationRelativeTo(null);//hiển thị giữa màn hình
        this.setTitle("Đăng nhập");
        this.setDefaultCloseOperation(EXIT_ON_CLOSE);//thoát chương trình khi bấm exit
        this.setVisible(true);//chạy chương trình
        panel_datve2.setVisible(true);
        HienThiNgayChieu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel10 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        panel_exit = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        panel_dong = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        panel_datve2 = new javax.swing.JPanel();
        jLabel49 = new javax.swing.JLabel();
        CBB_NgayChieu = new javax.swing.JComboBox<>();
        Lbl_NgayChieu = new javax.swing.JLabel();
        jComboBox18 = new javax.swing.JComboBox<>();
        jLabel51 = new javax.swing.JLabel();
        jComboBox19 = new javax.swing.JComboBox<>();
        jPanel49 = new javax.swing.JPanel();
        jLabel52 = new javax.swing.JLabel();
        jPanel50 = new javax.swing.JPanel();
        jPanel51 = new javax.swing.JPanel();
        jPanel52 = new javax.swing.JPanel();
        jLabel53 = new javax.swing.JLabel();
        jButton166 = new javax.swing.JButton();
        jButton167 = new javax.swing.JButton();
        jButton168 = new javax.swing.JButton();
        jButton169 = new javax.swing.JButton();
        jButton170 = new javax.swing.JButton();
        jButton171 = new javax.swing.JButton();
        jButton172 = new javax.swing.JButton();
        jButton173 = new javax.swing.JButton();
        jButton174 = new javax.swing.JButton();
        jButton175 = new javax.swing.JButton();
        jButton176 = new javax.swing.JButton();
        jButton177 = new javax.swing.JButton();
        jButton178 = new javax.swing.JButton();
        jButton179 = new javax.swing.JButton();
        jButton180 = new javax.swing.JButton();
        jButton181 = new javax.swing.JButton();
        jButton182 = new javax.swing.JButton();
        jButton183 = new javax.swing.JButton();
        jButton184 = new javax.swing.JButton();
        jButton185 = new javax.swing.JButton();
        jButton186 = new javax.swing.JButton();
        jButton187 = new javax.swing.JButton();
        jButton188 = new javax.swing.JButton();
        jButton189 = new javax.swing.JButton();
        jButton190 = new javax.swing.JButton();
        jButton191 = new javax.swing.JButton();
        jButton192 = new javax.swing.JButton();
        jButton193 = new javax.swing.JButton();
        jButton194 = new javax.swing.JButton();
        jButton195 = new javax.swing.JButton();
        jButton196 = new javax.swing.JButton();
        jButton197 = new javax.swing.JButton();
        jPanel53 = new javax.swing.JPanel();
        jLabel54 = new javax.swing.JLabel();
        jPanel54 = new javax.swing.JPanel();
        jPanel55 = new javax.swing.JPanel();
        jPanel56 = new javax.swing.JPanel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jButton198 = new javax.swing.JButton();
        jLabel58 = new javax.swing.JLabel();
        CBB_LoaiPhim = new javax.swing.JComboBox<>();
        Btn_XacNhan = new java.awt.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel10.setBackground(new java.awt.Color(0, 102, 102));

        jPanel12.setBackground(new java.awt.Color(0, 153, 153));

        panel_exit.setBackground(new java.awt.Color(0, 153, 153));
        panel_exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panel_exitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panel_exitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panel_exitMouseExited(evt);
            }
        });
        panel_exit.setLayout(null);

        jLabel8.setFont(new java.awt.Font("Dubai Medium", 1, 24)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("X");
        panel_exit.add(jLabel8);
        jLabel8.setBounds(0, 10, 30, 20);

        panel_dong.setBackground(new java.awt.Color(0, 153, 153));
        panel_dong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panel_dongMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panel_dongMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panel_dongMouseExited(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("_");
        jLabel13.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout panel_dongLayout = new javax.swing.GroupLayout(panel_dong);
        panel_dong.setLayout(panel_dongLayout);
        panel_dongLayout.setHorizontalGroup(
            panel_dongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_dongLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(42, 42, 42))
        );
        panel_dongLayout.setVerticalGroup(
            panel_dongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_dongLayout.createSequentialGroup()
                .addComponent(jLabel13)
                .addGap(0, 31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addContainerGap(1025, Short.MAX_VALUE)
                .addComponent(panel_dong, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_exit, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_exit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panel_dong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        panel_datve2.setBackground(new java.awt.Color(0, 102, 102));
        panel_datve2.setLayout(null);

        jLabel49.setForeground(new java.awt.Color(255, 255, 255));
        jLabel49.setText("Phim:");
        panel_datve2.add(jLabel49);
        jLabel49.setBounds(50, 140, 40, 20);

        CBB_NgayChieu.setBackground(new java.awt.Color(0, 153, 153));
        CBB_NgayChieu.setForeground(new java.awt.Color(255, 255, 255));
        CBB_NgayChieu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ngày chiếu" }));
        CBB_NgayChieu.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CBB_NgayChieuItemStateChanged(evt);
            }
        });
        CBB_NgayChieu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CBB_NgayChieuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CBB_NgayChieuMouseEntered(evt);
            }
        });
        CBB_NgayChieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBB_NgayChieuActionPerformed(evt);
            }
        });
        panel_datve2.add(CBB_NgayChieu);
        CBB_NgayChieu.setBounds(90, 40, 330, 22);

        Lbl_NgayChieu.setForeground(new java.awt.Color(255, 255, 255));
        Lbl_NgayChieu.setText("Ngày chiếu:");
        panel_datve2.add(Lbl_NgayChieu);
        Lbl_NgayChieu.setBounds(10, 40, 70, 16);

        jComboBox18.setBackground(new java.awt.Color(0, 153, 153));
        jComboBox18.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox18.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Phim" }));
        panel_datve2.add(jComboBox18);
        jComboBox18.setBounds(90, 140, 330, 22);

        jLabel51.setForeground(new java.awt.Color(255, 255, 255));
        jLabel51.setText("Suất chiếu: ");
        panel_datve2.add(jLabel51);
        jLabel51.setBounds(20, 190, 70, 16);

        jComboBox19.setBackground(new java.awt.Color(0, 153, 153));
        jComboBox19.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox19.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Suất chiếu" }));
        panel_datve2.add(jComboBox19);
        jComboBox19.setBounds(90, 190, 330, 22);

        jPanel49.setBackground(new java.awt.Color(153, 153, 153));
        jPanel49.setLayout(null);

        jLabel52.setFont(new java.awt.Font("Goudy Stout", 1, 18)); // NOI18N
        jLabel52.setText("Universo Cinemas");
        jPanel49.add(jLabel52);
        jLabel52.setBounds(30, 10, 340, 40);

        panel_datve2.add(jPanel49);
        jPanel49.setBounds(10, 260, 410, 340);

        jPanel50.setBackground(new java.awt.Color(0, 153, 153));
        jPanel50.setLayout(null);

        jPanel51.setBackground(new java.awt.Color(0, 153, 153));
        jPanel51.setLayout(null);
        jPanel50.add(jPanel51);
        jPanel51.setBounds(270, 430, 190, 20);

        panel_datve2.add(jPanel50);
        jPanel50.setBounds(450, 20, 10, 590);

        jPanel52.setBackground(new java.awt.Color(0, 153, 153));
        jPanel52.setLayout(null);

        jLabel53.setFont(new java.awt.Font("DialogInput", 1, 36)); // NOI18N
        jLabel53.setForeground(new java.awt.Color(255, 255, 255));
        jLabel53.setText("MÀN HÌNH");
        jPanel52.add(jLabel53);
        jLabel53.setBounds(190, 0, 190, 40);

        panel_datve2.add(jPanel52);
        jPanel52.setBounds(490, 40, 570, 50);

        jButton166.setBackground(new java.awt.Color(0, 153, 153));
        jButton166.setText("E6");
        panel_datve2.add(jButton166);
        jButton166.setBounds(990, 420, 70, 50);

        jButton167.setBackground(new java.awt.Color(0, 153, 153));
        jButton167.setText("C6");
        panel_datve2.add(jButton167);
        jButton167.setBounds(990, 280, 70, 50);

        jButton168.setBackground(new java.awt.Color(0, 153, 153));
        jButton168.setText("E2");
        panel_datve2.add(jButton168);
        jButton168.setBounds(570, 420, 70, 50);

        jButton169.setBackground(new java.awt.Color(0, 153, 153));
        jButton169.setText("E3");
        panel_datve2.add(jButton169);
        jButton169.setBounds(650, 420, 70, 50);

        jButton170.setBackground(new java.awt.Color(0, 153, 153));
        jButton170.setText("E4");
        panel_datve2.add(jButton170);
        jButton170.setBounds(830, 420, 70, 50);

        jButton171.setBackground(new java.awt.Color(0, 153, 153));
        jButton171.setText("E5");
        panel_datve2.add(jButton171);
        jButton171.setBounds(910, 420, 70, 50);

        jButton172.setBackground(new java.awt.Color(0, 153, 153));
        jButton172.setText("E1");
        panel_datve2.add(jButton172);
        jButton172.setBounds(490, 420, 70, 50);

        jButton173.setBackground(new java.awt.Color(0, 153, 153));
        jButton173.setText("A1");
        jButton173.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton173ActionPerformed(evt);
            }
        });
        panel_datve2.add(jButton173);
        jButton173.setBounds(490, 140, 70, 50);

        jButton174.setBackground(new java.awt.Color(0, 153, 153));
        jButton174.setText("A2");
        panel_datve2.add(jButton174);
        jButton174.setBounds(570, 140, 70, 50);

        jButton175.setBackground(new java.awt.Color(0, 153, 153));
        jButton175.setText("A3");
        panel_datve2.add(jButton175);
        jButton175.setBounds(650, 140, 70, 50);

        jButton176.setBackground(new java.awt.Color(0, 153, 153));
        jButton176.setText("A4");
        panel_datve2.add(jButton176);
        jButton176.setBounds(830, 140, 70, 50);

        jButton177.setBackground(new java.awt.Color(0, 153, 153));
        jButton177.setText("A5");
        panel_datve2.add(jButton177);
        jButton177.setBounds(910, 140, 70, 50);

        jButton178.setBackground(new java.awt.Color(0, 153, 153));
        jButton178.setText("A6");
        panel_datve2.add(jButton178);
        jButton178.setBounds(990, 140, 70, 50);

        jButton179.setBackground(new java.awt.Color(0, 153, 153));
        jButton179.setText("B6");
        panel_datve2.add(jButton179);
        jButton179.setBounds(990, 210, 70, 50);

        jButton180.setBackground(new java.awt.Color(0, 153, 153));
        jButton180.setText("B5");
        panel_datve2.add(jButton180);
        jButton180.setBounds(910, 210, 70, 50);

        jButton181.setBackground(new java.awt.Color(0, 153, 153));
        jButton181.setText("B4");
        panel_datve2.add(jButton181);
        jButton181.setBounds(830, 210, 70, 50);

        jButton182.setBackground(new java.awt.Color(0, 153, 153));
        jButton182.setText("B3");
        panel_datve2.add(jButton182);
        jButton182.setBounds(650, 210, 70, 50);

        jButton183.setBackground(new java.awt.Color(0, 153, 153));
        jButton183.setText("B2");
        panel_datve2.add(jButton183);
        jButton183.setBounds(570, 210, 70, 50);

        jButton184.setBackground(new java.awt.Color(0, 153, 153));
        jButton184.setText("B1");
        panel_datve2.add(jButton184);
        jButton184.setBounds(490, 210, 70, 50);

        jButton185.setBackground(new java.awt.Color(0, 153, 153));
        jButton185.setText("D6");
        panel_datve2.add(jButton185);
        jButton185.setBounds(990, 350, 70, 50);

        jButton186.setBackground(new java.awt.Color(0, 153, 153));
        jButton186.setText("C2");
        panel_datve2.add(jButton186);
        jButton186.setBounds(570, 280, 70, 50);

        jButton187.setBackground(new java.awt.Color(0, 153, 153));
        jButton187.setText("C3");
        panel_datve2.add(jButton187);
        jButton187.setBounds(650, 280, 70, 50);

        jButton188.setBackground(new java.awt.Color(0, 153, 153));
        jButton188.setText("C4");
        panel_datve2.add(jButton188);
        jButton188.setBounds(830, 280, 70, 50);

        jButton189.setBackground(new java.awt.Color(0, 153, 153));
        jButton189.setText("C5");
        panel_datve2.add(jButton189);
        jButton189.setBounds(910, 280, 70, 50);

        jButton190.setBackground(new java.awt.Color(0, 153, 153));
        jButton190.setText("C1");
        panel_datve2.add(jButton190);
        jButton190.setBounds(490, 280, 70, 50);

        jButton191.setBackground(new java.awt.Color(0, 153, 153));
        jButton191.setText("D1");
        panel_datve2.add(jButton191);
        jButton191.setBounds(490, 350, 70, 50);

        jButton192.setBackground(new java.awt.Color(0, 153, 153));
        jButton192.setText("D2");
        panel_datve2.add(jButton192);
        jButton192.setBounds(570, 350, 70, 50);

        jButton193.setBackground(new java.awt.Color(0, 153, 153));
        jButton193.setText("D3");
        panel_datve2.add(jButton193);
        jButton193.setBounds(650, 350, 70, 50);

        jButton194.setBackground(new java.awt.Color(0, 153, 153));
        jButton194.setText("D4");
        panel_datve2.add(jButton194);
        jButton194.setBounds(830, 350, 70, 50);

        jButton195.setBackground(new java.awt.Color(0, 153, 153));
        jButton195.setText("D5");
        panel_datve2.add(jButton195);
        jButton195.setBounds(910, 350, 70, 50);

        jButton196.setBackground(new java.awt.Color(102, 102, 0));
        jButton196.setForeground(new java.awt.Color(255, 255, 255));
        jButton196.setText("Huỷ");
        panel_datve2.add(jButton196);
        jButton196.setBounds(950, 560, 110, 40);

        jButton197.setBackground(new java.awt.Color(102, 102, 0));
        jButton197.setForeground(new java.awt.Color(255, 255, 255));
        jButton197.setText("Đặt vé");
        jButton197.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton197ActionPerformed(evt);
            }
        });
        panel_datve2.add(jButton197);
        jButton197.setBounds(680, 560, 110, 40);

        jPanel53.setBackground(new java.awt.Color(0, 153, 153));
        jPanel53.setLayout(null);
        panel_datve2.add(jPanel53);
        jPanel53.setBounds(460, 480, 620, 10);

        jLabel54.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel54.setForeground(new java.awt.Color(255, 255, 255));
        jLabel54.setText("Tổng tiền :");
        panel_datve2.add(jLabel54);
        jLabel54.setBounds(470, 500, 100, 30);

        jPanel54.setBackground(new java.awt.Color(51, 102, 0));
        jPanel54.setLayout(null);
        panel_datve2.add(jPanel54);
        jPanel54.setBounds(830, 510, 20, 20);

        jPanel55.setBackground(new java.awt.Color(0, 153, 153));
        jPanel55.setLayout(null);
        panel_datve2.add(jPanel55);
        jPanel55.setBounds(970, 510, 20, 20);

        jPanel56.setBackground(new java.awt.Color(255, 51, 51));
        jPanel56.setLayout(null);
        panel_datve2.add(jPanel56);
        jPanel56.setBounds(700, 510, 20, 20);

        jLabel55.setForeground(new java.awt.Color(255, 255, 255));
        jLabel55.setText("Ghế đã đặt");
        panel_datve2.add(jLabel55);
        jLabel55.setBounds(730, 510, 70, 16);

        jLabel56.setForeground(new java.awt.Color(255, 255, 255));
        jLabel56.setText("Ghế trống");
        panel_datve2.add(jLabel56);
        jLabel56.setBounds(1000, 510, 80, 16);

        jLabel57.setForeground(new java.awt.Color(255, 255, 255));
        jLabel57.setText("Ghế đã chọn");
        panel_datve2.add(jLabel57);
        jLabel57.setBounds(860, 510, 80, 16);

        jButton198.setBackground(new java.awt.Color(102, 102, 0));
        jButton198.setForeground(new java.awt.Color(255, 255, 255));
        jButton198.setText("Thanh Toán");
        jButton198.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton198ActionPerformed(evt);
            }
        });
        panel_datve2.add(jButton198);
        jButton198.setBounds(820, 560, 110, 40);

        jLabel58.setForeground(new java.awt.Color(255, 255, 255));
        jLabel58.setText("Loại phim:");
        panel_datve2.add(jLabel58);
        jLabel58.setBounds(20, 90, 70, 16);

        CBB_LoaiPhim.setBackground(new java.awt.Color(0, 153, 153));
        CBB_LoaiPhim.setForeground(new java.awt.Color(255, 255, 255));
        CBB_LoaiPhim.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Loại Phim" }));
        CBB_LoaiPhim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBB_LoaiPhimActionPerformed(evt);
            }
        });
        panel_datve2.add(CBB_LoaiPhim);
        CBB_LoaiPhim.setBounds(90, 90, 330, 22);

        Btn_XacNhan.setLabel("Xác Nhận");
        Btn_XacNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_XacNhanActionPerformed(evt);
            }
        });
        panel_datve2.add(Btn_XacNhan);
        Btn_XacNhan.setBounds(280, 230, 140, 24);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1092, Short.MAX_VALUE)
            .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panel_datve2, javax.swing.GroupLayout.DEFAULT_SIZE, 1092, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 690, Short.MAX_VALUE)
            .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel10Layout.createSequentialGroup()
                    .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 635, Short.MAX_VALUE)))
            .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                    .addGap(0, 41, Short.MAX_VALUE)
                    .addComponent(panel_datve2, javax.swing.GroupLayout.PREFERRED_SIZE, 633, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void panel_dongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_dongMouseClicked
        this.setState(ThemTV.ICONIFIED);//đóng
    }//GEN-LAST:event_panel_dongMouseClicked

    private void panel_dongMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_dongMouseEntered
        panel_dong.setBackground(new Color(162, 222, 208));
    }//GEN-LAST:event_panel_dongMouseEntered

    private void panel_dongMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_dongMouseExited
        panel_dong.setBackground(new Color(0,153,153));
    }//GEN-LAST:event_panel_dongMouseExited

    private void panel_exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_exitMouseClicked
        this.dispose(); //tắt tab
    }//GEN-LAST:event_panel_exitMouseClicked

    private void panel_exitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_exitMouseEntered
        panel_exit.setBackground(new Color(162, 222, 208));
    }//GEN-LAST:event_panel_exitMouseEntered

    private void panel_exitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_exitMouseExited
        panel_exit.setBackground(new Color(0,153,153));
    }//GEN-LAST:event_panel_exitMouseExited

    private void jButton173ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton173ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton173ActionPerformed

    private void jButton197ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton197ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton197ActionPerformed

    private void jButton198ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton198ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton198ActionPerformed

    private void CBB_LoaiPhimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBB_LoaiPhimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBB_LoaiPhimActionPerformed

    private void Btn_XacNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_XacNhanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_XacNhanActionPerformed

    private void CBB_NgayChieuItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CBB_NgayChieuItemStateChanged

    
    }//GEN-LAST:event_CBB_NgayChieuItemStateChanged

    private void CBB_NgayChieuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CBB_NgayChieuMouseClicked

    }//GEN-LAST:event_CBB_NgayChieuMouseClicked

    private void CBB_NgayChieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBB_NgayChieuActionPerformed
        HienThiLoaiPhim();
    }//GEN-LAST:event_CBB_NgayChieuActionPerformed

    private void CBB_NgayChieuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CBB_NgayChieuMouseEntered

    }//GEN-LAST:event_CBB_NgayChieuMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        DatVe datVe = new DatVe();
         
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button Btn_XacNhan;
    private javax.swing.JComboBox<String> CBB_LoaiPhim;
    private javax.swing.JComboBox<String> CBB_NgayChieu;
    private javax.swing.JLabel Lbl_NgayChieu;
    private javax.swing.JButton jButton166;
    private javax.swing.JButton jButton167;
    private javax.swing.JButton jButton168;
    private javax.swing.JButton jButton169;
    private javax.swing.JButton jButton170;
    private javax.swing.JButton jButton171;
    private javax.swing.JButton jButton172;
    private javax.swing.JButton jButton173;
    private javax.swing.JButton jButton174;
    private javax.swing.JButton jButton175;
    private javax.swing.JButton jButton176;
    private javax.swing.JButton jButton177;
    private javax.swing.JButton jButton178;
    private javax.swing.JButton jButton179;
    private javax.swing.JButton jButton180;
    private javax.swing.JButton jButton181;
    private javax.swing.JButton jButton182;
    private javax.swing.JButton jButton183;
    private javax.swing.JButton jButton184;
    private javax.swing.JButton jButton185;
    private javax.swing.JButton jButton186;
    private javax.swing.JButton jButton187;
    private javax.swing.JButton jButton188;
    private javax.swing.JButton jButton189;
    private javax.swing.JButton jButton190;
    private javax.swing.JButton jButton191;
    private javax.swing.JButton jButton192;
    private javax.swing.JButton jButton193;
    private javax.swing.JButton jButton194;
    private javax.swing.JButton jButton195;
    private javax.swing.JButton jButton196;
    private javax.swing.JButton jButton197;
    private javax.swing.JButton jButton198;
    private javax.swing.JComboBox<String> jComboBox18;
    private javax.swing.JComboBox<String> jComboBox19;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel49;
    private javax.swing.JPanel jPanel50;
    private javax.swing.JPanel jPanel51;
    private javax.swing.JPanel jPanel52;
    private javax.swing.JPanel jPanel53;
    private javax.swing.JPanel jPanel54;
    private javax.swing.JPanel jPanel55;
    private javax.swing.JPanel jPanel56;
    private javax.swing.JPanel panel_datve2;
    private javax.swing.JPanel panel_dong;
    private javax.swing.JPanel panel_exit;
    // End of variables declaration//GEN-END:variables

    private void HienThiNgayChieu() {
        SuatChieu_ctrl scc = new SuatChieu_ctrl();
        Vector<String> ListNgayChieu = new Vector<String>();
        ListNgayChieu = scc.ListNgayChieu();
        CBB_NgayChieu.setModel(new DefaultComboBoxModel<String>(ListNgayChieu.toArray(new String[ListNgayChieu.size()])));
    }
    private void HienThiLoaiPhim(){
        String NgayChieu = CBB_NgayChieu.getSelectedItem().toString();
        SuatChieu_ctrl scc = new SuatChieu_ctrl();
        Vector<String> ListLoaiPhim = new Vector<String>();
        ListLoaiPhim= scc.ListLoaiPhim(NgayChieu);
        CBB_LoaiPhim.setModel(new DefaultComboBoxModel<String>(ListLoaiPhim.toArray(new String[ListLoaiPhim.size()])));
    }
}
