/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;
//hello
import java.awt.Color;

/**
 *
 * @author Phon
 */
public class Home extends javax.swing.JFrame {

    public Home() {
        initComponents();
        
        this.setLocationRelativeTo(null);//hi?n th? gi?a m�n h�nh
        this.setTitle("Home");
        this.setDefaultCloseOperation(EXIT_ON_CLOSE);//tho�t ch??ng tr�nh khi b?m exit
        this.setVisible(true);//ch?y ch??ng tr�nh
        panel_thanhvien.setVisible(false);
        
//        panel_datve1.setVisible(false);
//        panel_datve2.setVisible(false);
//        panel_datve3.setVisible(false);
//        panel_datve4.setVisible(false);
//        panel_datve5.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel19 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        but_phongchieu = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        but_baocao = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        but_hoadon = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        but_nhanvien = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        but_taikhoan = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        panel_center = new javax.swing.JPanel();
        panel_trangchu = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        butt_thanhvien = new javax.swing.JPanel();
        label_thanhvien = new javax.swing.JLabel();
        butt_sanpham = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        butt_datve = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        butt_phim = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        butt_loaiphim = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        butt_lichchieu = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        panel_DatVe = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        but_datve_qlbv = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        but_tracuuve_qlbv = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        panel_lichchieu = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        panel_taikhoan = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        panel_loaiphim = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        panel_phim = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jPanel24 = new javax.swing.JPanel();
        jPanel25 = new javax.swing.JPanel();
        jPanel26 = new javax.swing.JPanel();
        jPanel27 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jPanel28 = new javax.swing.JPanel();
        jPanel29 = new javax.swing.JPanel();
        panel_nhanvien = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        panel_hoadon = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        panel_sanpham = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        panel_phongchieu = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        panel_baocao = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        panel_thanhvien = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        butt_themthanhvien = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        butt_tracuuthanhvien = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(243, 249, 250));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel2MouseEntered(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Administrator\\Desktop\\icons\\film (3).png")); // NOI18N
        jLabel2.setText("jLabel2");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        but_phongchieu.setBackground(new java.awt.Color(0, 153, 153));
        but_phongchieu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                but_phongchieuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                but_phongchieuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                but_phongchieuMouseExited(evt);
            }
        });
        but_phongchieu.setLayout(null);

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\Administrator\\Desktop\\icons\\room.png")); // NOI18N
        jLabel6.setText("Phòng Chiếu");
        but_phongchieu.add(jLabel6);
        jLabel6.setBounds(30, 10, 130, 40);

        but_baocao.setBackground(new java.awt.Color(0, 153, 153));
        but_baocao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                but_baocaoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                but_baocaoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                but_baocaoMouseExited(evt);
            }
        });
        but_baocao.setLayout(null);

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\Administrator\\Desktop\\icons\\report.png")); // NOI18N
        jLabel5.setText(" Báo Cáo");
        but_baocao.add(jLabel5);
        jLabel5.setBounds(30, 10, 120, 32);

        but_hoadon.setBackground(new java.awt.Color(0, 153, 153));
        but_hoadon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                but_hoadonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                but_hoadonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                but_hoadonMouseExited(evt);
            }
        });
        but_hoadon.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Administrator\\Desktop\\icons\\bill.png")); // NOI18N
        jLabel4.setText(" Hoá Đơn");
        but_hoadon.add(jLabel4);
        jLabel4.setBounds(30, 20, 130, 30);

        but_nhanvien.setBackground(new java.awt.Color(0, 153, 153));
        but_nhanvien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                but_nhanvienMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                but_nhanvienMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                but_nhanvienMouseExited(evt);
            }
        });
        but_nhanvien.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Administrator\\Desktop\\icons\\people.png")); // NOI18N
        jLabel3.setText(" Nhân Viên");
        but_nhanvien.add(jLabel3);
        jLabel3.setBounds(30, 20, 120, 30);

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\Administrator\\Desktop\\icons\\logout.png")); // NOI18N
        jLabel8.setText("jLabel8");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });

        but_taikhoan.setBackground(new java.awt.Color(0, 153, 153));
        but_taikhoan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                but_taikhoanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                but_taikhoanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                but_taikhoanMouseExited(evt);
            }
        });
        but_taikhoan.setLayout(null);

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\Administrator\\Desktop\\icons\\profile.png")); // NOI18N
        jLabel7.setText(" Tài Khoản");
        but_taikhoan.add(jLabel7);
        jLabel7.setBounds(30, 10, 120, 40);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(but_phongchieu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(but_baocao, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(but_hoadon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(but_nhanvien, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(but_taikhoan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel2)
                .addGap(34, 34, 34)
                .addComponent(but_taikhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(but_nhanvien, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(but_hoadon, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(but_phongchieu, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(but_baocao, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 190, 620);

        panel_trangchu.setBackground(new java.awt.Color(0, 102, 102));

        jPanel3.setBackground(new java.awt.Color(0, 204, 204));

        jLabel1.setFont(new java.awt.Font("Ink Free", 1, 48)); // NOI18N
        jLabel1.setText("Welcome To Universal Cinemas");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 701, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        butt_thanhvien.setBackground(new java.awt.Color(255, 255, 255));
        butt_thanhvien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                butt_thanhvienMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                butt_thanhvienMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                butt_thanhvienMouseExited(evt);
            }
        });
        butt_thanhvien.setLayout(null);

        label_thanhvien.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        label_thanhvien.setIcon(new javax.swing.ImageIcon("C:\\Users\\Administrator\\Desktop\\icons\\member.png")); // NOI18N
        label_thanhvien.setText(" Thành Viên");
        butt_thanhvien.add(label_thanhvien);
        label_thanhvien.setBounds(20, 10, 243, 104);

        butt_sanpham.setBackground(new java.awt.Color(255, 255, 255));
        butt_sanpham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                butt_sanphamMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                butt_sanphamMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                butt_sanphamMouseExited(evt);
            }
        });
        butt_sanpham.setLayout(null);

        jLabel13.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setIcon(new javax.swing.ImageIcon("C:\\Users\\Administrator\\Desktop\\icons\\popcorn.png")); // NOI18N
        jLabel13.setText(" Sản Phẩm");
        butt_sanpham.add(jLabel13);
        jLabel13.setBounds(0, 0, 320, 110);

        butt_datve.setBackground(new java.awt.Color(255, 255, 255));
        butt_datve.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                butt_datveMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                butt_datveMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                butt_datveMouseExited(evt);
            }
        });
        butt_datve.setLayout(null);

        jLabel11.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setIcon(new javax.swing.ImageIcon("C:\\Users\\Administrator\\Desktop\\icons\\ticket.png")); // NOI18N
        jLabel11.setText(" Đặt Vé");
        butt_datve.add(jLabel11);
        jLabel11.setBounds(23, 4, 280, 110);

        butt_phim.setBackground(new java.awt.Color(255, 255, 255));
        butt_phim.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                butt_phimMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                butt_phimMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                butt_phimMouseExited(evt);
            }
        });
        butt_phim.setLayout(null);

        jLabel14.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        jLabel14.setIcon(new javax.swing.ImageIcon("C:\\Users\\Administrator\\Desktop\\icons\\phim.png")); // NOI18N
        jLabel14.setText("  Phim");
        butt_phim.add(jLabel14);
        jLabel14.setBounds(30, 10, 243, 104);

        butt_loaiphim.setBackground(new java.awt.Color(255, 255, 255));
        butt_loaiphim.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                butt_loaiphimMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                butt_loaiphimMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                butt_loaiphimMouseExited(evt);
            }
        });
        butt_loaiphim.setLayout(null);

        jLabel12.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        jLabel12.setIcon(new javax.swing.ImageIcon("C:\\Users\\Administrator\\Desktop\\icons\\cinema.png")); // NOI18N
        jLabel12.setText("  Loại Phim");
        butt_loaiphim.add(jLabel12);
        jLabel12.setBounds(30, 10, 280, 104);

        butt_lichchieu.setBackground(new java.awt.Color(255, 255, 255));
        butt_lichchieu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                butt_lichchieuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                butt_lichchieuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                butt_lichchieuMouseExited(evt);
            }
        });
        butt_lichchieu.setLayout(null);

        jLabel32.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        jLabel32.setIcon(new javax.swing.ImageIcon("C:\\Users\\Administrator\\Desktop\\icons\\phim.png")); // NOI18N
        jLabel32.setText("  Lịch chiếu");
        butt_lichchieu.add(jLabel32);
        jLabel32.setBounds(30, 10, 243, 104);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(butt_thanhvien, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                    .addComponent(butt_phim, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                    .addComponent(butt_lichchieu, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(31, 31, 31)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(butt_loaiphim, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE)
                    .addComponent(butt_sanpham, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(butt_datve, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(butt_datve, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(butt_thanhvien, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(butt_sanpham, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(butt_phim, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(butt_loaiphim, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(butt_lichchieu, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout panel_trangchuLayout = new javax.swing.GroupLayout(panel_trangchu);
        panel_trangchu.setLayout(panel_trangchuLayout);
        panel_trangchuLayout.setHorizontalGroup(
            panel_trangchuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panel_trangchuLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(69, Short.MAX_VALUE))
        );
        panel_trangchuLayout.setVerticalGroup(
            panel_trangchuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_trangchuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        panel_DatVe.setLayout(null);

        jPanel18.setBackground(new java.awt.Color(0, 204, 204));

        jLabel29.setFont(new java.awt.Font("DialogInput", 1, 36)); // NOI18N
        jLabel29.setText("Quản Lý Bán Vé");

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel18Layout.createSequentialGroup()
                .addContainerGap(262, Short.MAX_VALUE)
                .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(199, 199, 199))
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel29)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        panel_DatVe.add(jPanel18);
        jPanel18.setBounds(0, 0, 870, 110);

        but_datve_qlbv.setBackground(new java.awt.Color(0, 204, 204));
        but_datve_qlbv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                but_datve_qlbvMouseClicked(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        jLabel22.setText("Đặt Vé");

        javax.swing.GroupLayout but_datve_qlbvLayout = new javax.swing.GroupLayout(but_datve_qlbv);
        but_datve_qlbv.setLayout(but_datve_qlbvLayout);
        but_datve_qlbvLayout.setHorizontalGroup(
            but_datve_qlbvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(but_datve_qlbvLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );
        but_datve_qlbvLayout.setVerticalGroup(
            but_datve_qlbvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, but_datve_qlbvLayout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addComponent(jLabel22)
                .addContainerGap())
        );

        panel_DatVe.add(but_datve_qlbv);
        but_datve_qlbv.setBounds(140, 310, 190, 50);

        but_tracuuve_qlbv.setBackground(new java.awt.Color(0, 204, 204));

        jLabel30.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        jLabel30.setText("Tra Cứu Vé");

        javax.swing.GroupLayout but_tracuuve_qlbvLayout = new javax.swing.GroupLayout(but_tracuuve_qlbv);
        but_tracuuve_qlbv.setLayout(but_tracuuve_qlbvLayout);
        but_tracuuve_qlbvLayout.setHorizontalGroup(
            but_tracuuve_qlbvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(but_tracuuve_qlbvLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel30)
                .addContainerGap(40, Short.MAX_VALUE))
        );
        but_tracuuve_qlbvLayout.setVerticalGroup(
            but_tracuuve_qlbvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, but_tracuuve_qlbvLayout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addComponent(jLabel30)
                .addContainerGap())
        );

        panel_DatVe.add(but_tracuuve_qlbv);
        but_tracuuve_qlbv.setBounds(510, 310, 190, 50);

        panel_lichchieu.setLayout(null);

        jPanel14.setBackground(new java.awt.Color(0, 204, 204));

        jLabel25.setFont(new java.awt.Font("DialogInput", 1, 36)); // NOI18N
        jLabel25.setText("Quản Lý Lịch chiếu");

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGap(218, 218, 218)
                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(243, Short.MAX_VALUE))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel25)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        panel_lichchieu.add(jPanel14);
        jPanel14.setBounds(0, 0, 870, 110);

        jPanel5.setBackground(new java.awt.Color(0, 204, 204));

        jLabel15.setFont(new java.awt.Font("DialogInput", 1, 36)); // NOI18N
        jLabel15.setText("Quản Lý Tài Khoản");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(216, 216, 216)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(272, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(jLabel15)
                .addContainerGap())
        );

        jPanel16.setBackground(new java.awt.Color(0, 204, 204));

        jLabel27.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        jLabel27.setIcon(new javax.swing.ImageIcon("C:\\Users\\Administrator\\Desktop\\icons\\profile.png")); // NOI18N
        jLabel27.setText(" Tạo tài khoản");

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel27)
                .addContainerGap(58, Short.MAX_VALUE))
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel17.setBackground(new java.awt.Color(0, 204, 204));

        jLabel28.setBackground(new java.awt.Color(0, 204, 204));
        jLabel28.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        jLabel28.setIcon(new javax.swing.ImageIcon("C:\\Users\\Administrator\\Downloads\\search.png")); // NOI18N
        jLabel28.setText("Tra cứu tài khoản");

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel28)
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel17Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel28, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout panel_taikhoanLayout = new javax.swing.GroupLayout(panel_taikhoan);
        panel_taikhoan.setLayout(panel_taikhoanLayout);
        panel_taikhoanLayout.setHorizontalGroup(
            panel_taikhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panel_taikhoanLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(94, 94, 94))
        );
        panel_taikhoanLayout.setVerticalGroup(
            panel_taikhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_taikhoanLayout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(203, 203, 203)
                .addGroup(panel_taikhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(321, Short.MAX_VALUE))
        );

        panel_loaiphim.setLayout(null);

        jPanel15.setBackground(new java.awt.Color(0, 204, 204));

        jLabel26.setFont(new java.awt.Font("DialogInput", 1, 36)); // NOI18N
        jLabel26.setText("Quản Lý Loại Phim");

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGap(218, 218, 218)
                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(243, Short.MAX_VALUE))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel26)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        panel_loaiphim.add(jPanel15);
        jPanel15.setBounds(0, 0, 870, 110);

        panel_phim.setLayout(null);

        jPanel13.setBackground(new java.awt.Color(0, 204, 204));

        jLabel24.setFont(new java.awt.Font("DialogInput", 1, 36)); // NOI18N
        jLabel24.setText("Quản Lý Phim");

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(263, 263, 263)
                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(301, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel24)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        panel_phim.add(jPanel13);
        jPanel13.setBounds(0, 0, 870, 90);

        jPanel24.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel24Layout = new javax.swing.GroupLayout(jPanel24);
        jPanel24.setLayout(jPanel24Layout);
        jPanel24Layout.setHorizontalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 190, Short.MAX_VALUE)
        );
        jPanel24Layout.setVerticalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );

        panel_phim.add(jPanel24);
        jPanel24.setBounds(650, 410, 190, 240);

        jPanel25.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel25Layout = new javax.swing.GroupLayout(jPanel25);
        jPanel25.setLayout(jPanel25Layout);
        jPanel25Layout.setHorizontalGroup(
            jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 190, Short.MAX_VALUE)
        );
        jPanel25Layout.setVerticalGroup(
            jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );

        panel_phim.add(jPanel25);
        jPanel25.setBounds(650, 110, 190, 240);

        jPanel26.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel26Layout = new javax.swing.GroupLayout(jPanel26);
        jPanel26.setLayout(jPanel26Layout);
        jPanel26Layout.setHorizontalGroup(
            jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 190, Short.MAX_VALUE)
        );
        jPanel26Layout.setVerticalGroup(
            jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );

        panel_phim.add(jPanel26);
        jPanel26.setBounds(340, 110, 190, 240);

        jPanel27.setBackground(new java.awt.Color(255, 255, 255));

        jLabel31.setText("jLabel31");

        javax.swing.GroupLayout jPanel27Layout = new javax.swing.GroupLayout(jPanel27);
        jPanel27.setLayout(jPanel27Layout);
        jPanel27Layout.setHorizontalGroup(
            jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel27Layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel27Layout.setVerticalGroup(
            jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel27Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(166, Short.MAX_VALUE))
        );

        panel_phim.add(jPanel27);
        jPanel27.setBounds(40, 110, 190, 240);

        jPanel28.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel28Layout = new javax.swing.GroupLayout(jPanel28);
        jPanel28.setLayout(jPanel28Layout);
        jPanel28Layout.setHorizontalGroup(
            jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 190, Short.MAX_VALUE)
        );
        jPanel28Layout.setVerticalGroup(
            jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );

        panel_phim.add(jPanel28);
        jPanel28.setBounds(40, 410, 190, 240);

        jPanel29.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel29Layout = new javax.swing.GroupLayout(jPanel29);
        jPanel29.setLayout(jPanel29Layout);
        jPanel29Layout.setHorizontalGroup(
            jPanel29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 190, Short.MAX_VALUE)
        );
        jPanel29Layout.setVerticalGroup(
            jPanel29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 240, Short.MAX_VALUE)
        );

        panel_phim.add(jPanel29);
        jPanel29.setBounds(340, 410, 190, 240);

        jPanel6.setBackground(new java.awt.Color(0, 204, 204));

        jLabel16.setFont(new java.awt.Font("DialogInput", 1, 36)); // NOI18N
        jLabel16.setText("Quản Lý Nhân Viên");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(232, 232, 232)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(255, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel16)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panel_nhanvienLayout = new javax.swing.GroupLayout(panel_nhanvien);
        panel_nhanvien.setLayout(panel_nhanvienLayout);
        panel_nhanvienLayout.setHorizontalGroup(
            panel_nhanvienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panel_nhanvienLayout.setVerticalGroup(
            panel_nhanvienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_nhanvienLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(544, Short.MAX_VALUE))
        );

        jPanel7.setBackground(new java.awt.Color(0, 204, 204));

        jLabel17.setFont(new java.awt.Font("DialogInput", 1, 36)); // NOI18N
        jLabel17.setText("Quản Lý Hoá Đơn");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(251, 251, 251)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(272, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel17)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panel_hoadonLayout = new javax.swing.GroupLayout(panel_hoadon);
        panel_hoadon.setLayout(panel_hoadonLayout);
        panel_hoadonLayout.setHorizontalGroup(
            panel_hoadonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panel_hoadonLayout.setVerticalGroup(
            panel_hoadonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_hoadonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(550, Short.MAX_VALUE))
        );

        panel_sanpham.setLayout(null);

        jPanel12.setBackground(new java.awt.Color(0, 204, 204));

        jLabel23.setFont(new java.awt.Font("DialogInput", 1, 36)); // NOI18N
        jLabel23.setText("Quản Lý Sản Phẩm");
        jLabel23.setToolTipText("");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(224, 224, 224)
                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(277, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(jLabel23)
                .addGap(20, 20, 20))
        );

        panel_sanpham.add(jPanel12);
        jPanel12.setBounds(0, 0, 870, 100);

        jPanel8.setBackground(new java.awt.Color(0, 204, 204));

        jLabel18.setFont(new java.awt.Font("DialogInput", 1, 36)); // NOI18N
        jLabel18.setText("Quản lý Phòng Chiếu");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(205, 205, 205)
                .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, 453, Short.MAX_VALUE)
                .addGap(212, 212, 212))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel18)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panel_phongchieuLayout = new javax.swing.GroupLayout(panel_phongchieu);
        panel_phongchieu.setLayout(panel_phongchieuLayout);
        panel_phongchieuLayout.setHorizontalGroup(
            panel_phongchieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panel_phongchieuLayout.setVerticalGroup(
            panel_phongchieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_phongchieuLayout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(541, Short.MAX_VALUE))
        );

        jPanel10.setBackground(new java.awt.Color(0, 204, 204));

        jLabel19.setFont(new java.awt.Font("DialogInput", 1, 36)); // NOI18N
        jLabel19.setText("Báo cáo, Thống kê");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(208, 208, 208)
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(211, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel19)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panel_baocaoLayout = new javax.swing.GroupLayout(panel_baocao);
        panel_baocao.setLayout(panel_baocaoLayout);
        panel_baocaoLayout.setHorizontalGroup(
            panel_baocaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panel_baocaoLayout.setVerticalGroup(
            panel_baocaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_baocaoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(571, Short.MAX_VALUE))
        );

        panel_thanhvien.setBackground(new java.awt.Color(204, 255, 255));

        jPanel9.setBackground(new java.awt.Color(0, 204, 204));

        jLabel20.setFont(new java.awt.Font("DialogInput", 1, 36)); // NOI18N
        jLabel20.setText("Quản Lý Thành Viên");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(216, 216, 216)
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(236, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(jLabel20)
                .addGap(36, 36, 36))
        );

        butt_themthanhvien.setBackground(new java.awt.Color(0, 204, 204));
        butt_themthanhvien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                butt_themthanhvienMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                butt_themthanhvienMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                butt_themthanhvienMouseExited(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\Administrator\\Desktop\\icons\\add-nhanvien.png")); // NOI18N
        jLabel10.setText(" Thêm thành viên");

        javax.swing.GroupLayout butt_themthanhvienLayout = new javax.swing.GroupLayout(butt_themthanhvien);
        butt_themthanhvien.setLayout(butt_themthanhvienLayout);
        butt_themthanhvienLayout.setHorizontalGroup(
            butt_themthanhvienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(butt_themthanhvienLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        butt_themthanhvienLayout.setVerticalGroup(
            butt_themthanhvienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, butt_themthanhvienLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        butt_tracuuthanhvien.setBackground(new java.awt.Color(0, 204, 204));
        butt_tracuuthanhvien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                butt_tracuuthanhvienMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                butt_tracuuthanhvienMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                butt_tracuuthanhvienMouseExited(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("DialogInput", 1, 18)); // NOI18N
        jLabel21.setIcon(new javax.swing.ImageIcon("C:\\Users\\Administrator\\Downloads\\smile.png")); // NOI18N
        jLabel21.setText(" Tra cứu thành viên");

        javax.swing.GroupLayout butt_tracuuthanhvienLayout = new javax.swing.GroupLayout(butt_tracuuthanhvien);
        butt_tracuuthanhvien.setLayout(butt_tracuuthanhvienLayout);
        butt_tracuuthanhvienLayout.setHorizontalGroup(
            butt_tracuuthanhvienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, butt_tracuuthanhvienLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel21)
                .addGap(26, 26, 26))
        );
        butt_tracuuthanhvienLayout.setVerticalGroup(
            butt_tracuuthanhvienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, butt_tracuuthanhvienLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel21)
                .addContainerGap())
        );

        javax.swing.GroupLayout panel_thanhvienLayout = new javax.swing.GroupLayout(panel_thanhvien);
        panel_thanhvien.setLayout(panel_thanhvienLayout);
        panel_thanhvienLayout.setHorizontalGroup(
            panel_thanhvienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panel_thanhvienLayout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addComponent(butt_themthanhvien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(butt_tracuuthanhvien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(93, 93, 93))
        );
        panel_thanhvienLayout.setVerticalGroup(
            panel_thanhvienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_thanhvienLayout.createSequentialGroup()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(189, 189, 189)
                .addGroup(panel_thanhvienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(butt_themthanhvien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(butt_tracuuthanhvien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 321, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panel_centerLayout = new javax.swing.GroupLayout(panel_center);
        panel_center.setLayout(panel_centerLayout);
        panel_centerLayout.setHorizontalGroup(
            panel_centerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_trangchu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panel_centerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panel_taikhoan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panel_centerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panel_nhanvien, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panel_centerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panel_hoadon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panel_centerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panel_phongchieu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panel_centerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panel_baocao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panel_centerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panel_thanhvien, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panel_centerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panel_sanpham, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 870, Short.MAX_VALUE))
            .addGroup(panel_centerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panel_phim, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 870, Short.MAX_VALUE))
            .addGroup(panel_centerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panel_loaiphim, javax.swing.GroupLayout.DEFAULT_SIZE, 870, Short.MAX_VALUE))
            .addGroup(panel_centerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panel_lichchieu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 870, Short.MAX_VALUE))
            .addGroup(panel_centerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panel_DatVe, javax.swing.GroupLayout.DEFAULT_SIZE, 870, Short.MAX_VALUE))
        );
        panel_centerLayout.setVerticalGroup(
            panel_centerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_trangchu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panel_centerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panel_taikhoan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panel_centerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panel_nhanvien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panel_centerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panel_hoadon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panel_centerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panel_phongchieu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panel_centerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panel_baocao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panel_centerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panel_thanhvien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panel_centerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panel_sanpham, javax.swing.GroupLayout.DEFAULT_SIZE, 673, Short.MAX_VALUE))
            .addGroup(panel_centerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panel_centerLayout.createSequentialGroup()
                    .addComponent(panel_phim, javax.swing.GroupLayout.PREFERRED_SIZE, 673, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(panel_centerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panel_centerLayout.createSequentialGroup()
                    .addComponent(panel_loaiphim, javax.swing.GroupLayout.PREFERRED_SIZE, 627, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 46, Short.MAX_VALUE)))
            .addGroup(panel_centerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panel_centerLayout.createSequentialGroup()
                    .addComponent(panel_lichchieu, javax.swing.GroupLayout.PREFERRED_SIZE, 619, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 54, Short.MAX_VALUE)))
            .addGroup(panel_centerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panel_centerLayout.createSequentialGroup()
                    .addComponent(panel_DatVe, javax.swing.GroupLayout.PREFERRED_SIZE, 623, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 50, Short.MAX_VALUE)))
        );

        jPanel1.add(panel_center);
        panel_center.setBounds(190, 0, 870, 620);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1058, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void but_nhanvienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_but_nhanvienMouseClicked
        panel_trangchu.setVisible(false);
        panel_taikhoan.setVisible(false);
        panel_nhanvien.setVisible(true);
        panel_hoadon.setVisible(false);
        panel_phongchieu.setVisible(false);
        panel_baocao.setVisible(false);
        panel_thanhvien.setVisible(false);
        panel_DatVe.setVisible(false);
        panel_sanpham.setVisible(false);
        panel_phim.setVisible(false);
        panel_lichchieu.setVisible(false);
        panel_loaiphim.setVisible(false);
//        panel_datve1.setVisible(false);
//        panel_datve2.setVisible(false);
//        panel_datve3.setVisible(false);
//        panel_datve4.setVisible(false);
//        panel_datve5.setVisible(false);
    }//GEN-LAST:event_but_nhanvienMouseClicked

    private void but_hoadonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_but_hoadonMouseClicked

        panel_trangchu.setVisible(false);
        panel_taikhoan.setVisible(false);
        panel_nhanvien.setVisible(false);
        panel_hoadon.setVisible(true);
        panel_phongchieu.setVisible(false);
        panel_baocao.setVisible(false);
        panel_thanhvien.setVisible(false);
        panel_DatVe.setVisible(false);
        panel_sanpham.setVisible(false);
        panel_phim.setVisible(false);
        panel_lichchieu.setVisible(false);
        panel_loaiphim.setVisible(false);
//        panel_datve1.setVisible(false);
//        panel_datve2.setVisible(false);
//        panel_datve3.setVisible(false);
//        panel_datve4.setVisible(false);
//        panel_datve5.setVisible(false);
    }//GEN-LAST:event_but_hoadonMouseClicked

    private void but_phongchieuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_but_phongchieuMouseClicked

        panel_trangchu.setVisible(false);
        panel_taikhoan.setVisible(false);
        panel_nhanvien.setVisible(false);
        panel_hoadon.setVisible(false);
        panel_phongchieu.setVisible(true);
        panel_taikhoan.setVisible(false);
        panel_thanhvien.setVisible(false);
        panel_DatVe.setVisible(false);
        panel_sanpham.setVisible(false);
        panel_phim.setVisible(false);
        panel_lichchieu.setVisible(false);
        panel_loaiphim.setVisible(false);
//        panel_datve1.setVisible(false);
//        panel_datve2.setVisible(false);
//        panel_datve3.setVisible(false);
//        panel_datve4.setVisible(false);
//        panel_datve5.setVisible(false);

    }//GEN-LAST:event_but_phongchieuMouseClicked

    private void but_baocaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_but_baocaoMouseClicked

        panel_trangchu.setVisible(false);
        panel_taikhoan.setVisible(false);
        panel_nhanvien.setVisible(false);
        panel_hoadon.setVisible(false);
        panel_phongchieu.setVisible(false);
        panel_baocao.setVisible(true);
        panel_thanhvien.setVisible(false);
        panel_DatVe.setVisible(false);
        panel_sanpham.setVisible(false);
        panel_phim.setVisible(false);
        panel_lichchieu.setVisible(false);
        panel_loaiphim.setVisible(false);
//        panel_datve1.setVisible(false);
//        panel_datve2.setVisible(false);
//        panel_datve3.setVisible(false);
//        panel_datve4.setVisible(false);
//        panel_datve5.setVisible(false);

    }//GEN-LAST:event_but_baocaoMouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        this.dispose();
        DangNhap dn = new DangNhap();


    }//GEN-LAST:event_jLabel8MouseClicked

    private void jPanel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseEntered

    }//GEN-LAST:event_jPanel2MouseEntered

    private void but_nhanvienMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_but_nhanvienMouseEntered
        but_nhanvien.setBackground(new Color(0, 204, 204));
    }//GEN-LAST:event_but_nhanvienMouseEntered

    private void but_nhanvienMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_but_nhanvienMouseExited
        but_nhanvien.setBackground(new Color(0, 153, 153));
    }//GEN-LAST:event_but_nhanvienMouseExited

    private void but_hoadonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_but_hoadonMouseEntered
        but_hoadon.setBackground(new Color(0, 204, 204));
    }//GEN-LAST:event_but_hoadonMouseEntered

    private void but_hoadonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_but_hoadonMouseExited
        but_hoadon.setBackground(new Color(0, 153, 153));
    }//GEN-LAST:event_but_hoadonMouseExited

    private void but_phongchieuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_but_phongchieuMouseEntered
        but_phongchieu.setBackground(new Color(0, 204, 204));
    }//GEN-LAST:event_but_phongchieuMouseEntered

    private void but_phongchieuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_but_phongchieuMouseExited
        but_phongchieu.setBackground(new Color(0, 153, 153));
    }//GEN-LAST:event_but_phongchieuMouseExited

    private void but_baocaoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_but_baocaoMouseEntered
        but_baocao.setBackground(new Color(0, 204, 204));
    }//GEN-LAST:event_but_baocaoMouseEntered

    private void but_baocaoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_but_baocaoMouseExited
        but_baocao.setBackground(new Color(0, 153, 153));
    }//GEN-LAST:event_but_baocaoMouseExited

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        panel_trangchu.setVisible(true);
        panel_taikhoan.setVisible(false);
        panel_nhanvien.setVisible(false);
        panel_hoadon.setVisible(false);
        panel_phongchieu.setVisible(false);
        panel_baocao.setVisible(false);
        panel_thanhvien.setVisible(false);
        panel_DatVe.setVisible(false);
        panel_sanpham.setVisible(false);
        panel_phim.setVisible(false);
        panel_lichchieu.setVisible(false);
        panel_loaiphim.setVisible(false);
//        panel_datve1.setVisible(false);
//        panel_datve2.setVisible(false);
//        panel_datve3.setVisible(false);
//        panel_datve4.setVisible(false);
//        panel_datve5.setVisible(false);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void but_taikhoanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_but_taikhoanMouseClicked
        panel_trangchu.setVisible(false);
        panel_taikhoan.setVisible(true);
        panel_nhanvien.setVisible(false);
        panel_hoadon.setVisible(false);
        panel_phongchieu.setVisible(false);
        panel_baocao.setVisible(false);
        panel_thanhvien.setVisible(false);
        panel_DatVe.setVisible(false);
        panel_sanpham.setVisible(false);
        panel_phim.setVisible(false);
        panel_lichchieu.setVisible(false);
        panel_loaiphim.setVisible(false);
//        panel_datve1.setVisible(false);
//        panel_datve2.setVisible(false);
//        panel_datve3.setVisible(false);
//        panel_datve4.setVisible(false);
//        panel_datve5.setVisible(false);
    }//GEN-LAST:event_but_taikhoanMouseClicked

    private void but_taikhoanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_but_taikhoanMouseEntered
        but_taikhoan.setBackground(new Color(0, 204, 204));
    }//GEN-LAST:event_but_taikhoanMouseEntered

    private void but_taikhoanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_but_taikhoanMouseExited
        but_taikhoan.setBackground(new Color(0, 153, 153));
    }//GEN-LAST:event_but_taikhoanMouseExited

    private void butt_datveMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butt_datveMouseEntered
        butt_datve.setBackground(new Color(238, 238, 238));
    }//GEN-LAST:event_butt_datveMouseEntered

    private void butt_datveMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butt_datveMouseExited
        butt_datve.setBackground(Color.white);
    }//GEN-LAST:event_butt_datveMouseExited

    private void butt_phimMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butt_phimMouseEntered
        butt_phim.setBackground(new Color(238, 238, 238));
    }//GEN-LAST:event_butt_phimMouseEntered

    private void butt_phimMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butt_phimMouseExited
        butt_phim.setBackground(Color.white);
    }//GEN-LAST:event_butt_phimMouseExited

    private void butt_sanphamMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butt_sanphamMouseEntered
        butt_sanpham.setBackground(new Color(238, 238, 238));
    }//GEN-LAST:event_butt_sanphamMouseEntered

    private void butt_sanphamMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butt_sanphamMouseExited
        butt_sanpham.setBackground(Color.white);
    }//GEN-LAST:event_butt_sanphamMouseExited

    private void butt_loaiphimMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butt_loaiphimMouseEntered
        butt_loaiphim.setBackground(new Color(238, 238, 238));
    }//GEN-LAST:event_butt_loaiphimMouseEntered

    private void butt_loaiphimMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butt_loaiphimMouseExited
        butt_loaiphim.setBackground(Color.white);
    }//GEN-LAST:event_butt_loaiphimMouseExited

    private void butt_thanhvienMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butt_thanhvienMouseEntered
        butt_thanhvien.setBackground(new Color(238, 238, 238));
    }//GEN-LAST:event_butt_thanhvienMouseEntered

    private void butt_thanhvienMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butt_thanhvienMouseExited
        butt_thanhvien.setBackground(Color.white);
    }//GEN-LAST:event_butt_thanhvienMouseExited
/*
    private void butt_l?chchieuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butt_l?chchieuMouseEntered
      
    }//GEN-LAST:event_butt_l?chchieuMouseEntered

    private void butt_l?chchieuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butt_l?chchieuMouseExited
       
    }//GEN-LAST:event_butt_l?chchieuMouseExited
*/
    private void butt_thanhvienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butt_thanhvienMouseClicked
        panel_thanhvien.setVisible(true);
        panel_trangchu.setVisible(false);
        panel_taikhoan.setVisible(false);
        panel_nhanvien.setVisible(false);
        panel_hoadon.setVisible(false);
        panel_phongchieu.setVisible(false);
        panel_baocao.setVisible(false);
        panel_DatVe.setVisible(false);
        panel_sanpham.setVisible(false);
        panel_phim.setVisible(false);
        panel_lichchieu.setVisible(false);
        panel_loaiphim.setVisible(false);
       
//        panel_datve1.setVisible(false);
//        panel_datve2.setVisible(false);
//        panel_datve3.setVisible(false);
//        panel_datve4.setVisible(false);
//        panel_datve5.setVisible(false);
    }//GEN-LAST:event_butt_thanhvienMouseClicked

    private void butt_themthanhvienMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butt_themthanhvienMouseEntered
        butt_themthanhvien.setBackground(new Color(35, 203, 167));
    }//GEN-LAST:event_butt_themthanhvienMouseEntered

    private void butt_tracuuthanhvienMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butt_tracuuthanhvienMouseEntered
        butt_tracuuthanhvien.setBackground(new Color(35, 203, 167));
    }//GEN-LAST:event_butt_tracuuthanhvienMouseEntered

    private void butt_themthanhvienMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butt_themthanhvienMouseExited
        butt_themthanhvien.setBackground(new Color(0, 204, 204));
    }//GEN-LAST:event_butt_themthanhvienMouseExited

    private void butt_tracuuthanhvienMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butt_tracuuthanhvienMouseExited
        butt_tracuuthanhvien.setBackground(new Color(0, 204, 204));
    }//GEN-LAST:event_butt_tracuuthanhvienMouseExited

    private void butt_themthanhvienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butt_themthanhvienMouseClicked
        ThemTV themtv = new ThemTV();
    }//GEN-LAST:event_butt_themthanhvienMouseClicked

    private void butt_tracuuthanhvienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butt_tracuuthanhvienMouseClicked
        TraCuuTV tracuutv = new TraCuuTV();
    }//GEN-LAST:event_butt_tracuuthanhvienMouseClicked

    private void butt_datveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butt_datveMouseClicked
        panel_thanhvien.setVisible(false);
        panel_trangchu.setVisible(false);
        panel_taikhoan.setVisible(false);
        panel_nhanvien.setVisible(false);
        panel_hoadon.setVisible(false);
        panel_phongchieu.setVisible(false);
        panel_baocao.setVisible(false);
        panel_DatVe.setVisible(true);
        panel_sanpham.setVisible(false);
        panel_phim.setVisible(false);
        panel_lichchieu.setVisible(false);
        panel_loaiphim.setVisible(false);
        
//        panel_datve1.setVisible(true);
//        panel_datve2.setVisible(false);
//        panel_datve3.setVisible(false);
//        panel_datve4.setVisible(false);
//        panel_datve5.setVisible(false);
    }//GEN-LAST:event_butt_datveMouseClicked

    private void butt_sanphamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butt_sanphamMouseClicked
        panel_thanhvien.setVisible(false);
        panel_trangchu.setVisible(false);
        panel_taikhoan.setVisible(false);
        panel_nhanvien.setVisible(false);
        panel_hoadon.setVisible(false);
        panel_phongchieu.setVisible(false);
        panel_baocao.setVisible(false);
        panel_DatVe.setVisible(false);
        panel_sanpham.setVisible(true);
        panel_phim.setVisible(false);
        panel_lichchieu.setVisible(false);
        panel_loaiphim.setVisible(false);
//        panel_datve1.setVisible(false);
//        panel_datve2.setVisible(false);
//        panel_datve3.setVisible(false);
//        panel_datve4.setVisible(false);
//        panel_datve5.setVisible(false);
    }//GEN-LAST:event_butt_sanphamMouseClicked

    private void butt_phimMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butt_phimMouseClicked
        panel_thanhvien.setVisible(false);
        panel_trangchu.setVisible(false);
        panel_taikhoan.setVisible(false);
        panel_nhanvien.setVisible(false);
        panel_hoadon.setVisible(false);
        panel_phongchieu.setVisible(false);
        panel_baocao.setVisible(false);
        panel_DatVe.setVisible(false);
        panel_sanpham.setVisible(false);
        panel_phim.setVisible(true);
        panel_lichchieu.setVisible(false);
        panel_loaiphim.setVisible(false);
//        panel_datve1.setVisible(false);
//        panel_datve2.setVisible(false);
//        panel_datve3.setVisible(false);
//        panel_datve4.setVisible(false);
//        panel_datve5.setVisible(false);
    }//GEN-LAST:event_butt_phimMouseClicked
/*
    private void butt_l?chchieuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butt_l?chchieuMouseClicked
       
    }//GEN-LAST:event_butt_l?chchieuMouseClicked
*/
    private void butt_loaiphimMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butt_loaiphimMouseClicked
        panel_thanhvien.setVisible(false);
        panel_trangchu.setVisible(false);
        panel_taikhoan.setVisible(false);
        panel_nhanvien.setVisible(false);
        panel_hoadon.setVisible(false);
        panel_phongchieu.setVisible(false);
        panel_baocao.setVisible(false);
        panel_DatVe.setVisible(false);
        panel_sanpham.setVisible(false);
        panel_phim.setVisible(false);
        panel_lichchieu.setVisible(false);
        panel_loaiphim.setVisible(true);
//       
    }//GEN-LAST:event_butt_loaiphimMouseClicked

    private void but_datve_qlbvMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_but_datve_qlbvMouseClicked
        DatVe datve = new DatVe();
    }//GEN-LAST:event_but_datve_qlbvMouseClicked

    private void butt_lichchieuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butt_lichchieuMouseClicked
       panel_thanhvien.setVisible(false);
        panel_trangchu.setVisible(false);
        panel_taikhoan.setVisible(false);
        panel_nhanvien.setVisible(false);
        panel_hoadon.setVisible(false);
        panel_phongchieu.setVisible(false);
        panel_baocao.setVisible(false);
        panel_DatVe.setVisible(false);
        panel_sanpham.setVisible(false);
        panel_phim.setVisible(false);
        panel_lichchieu.setVisible(true);
        panel_loaiphim.setVisible(false);
    }//GEN-LAST:event_butt_lichchieuMouseClicked

    private void butt_lichchieuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butt_lichchieuMouseEntered
       butt_lichchieu.setBackground(new Color(238, 238, 238));
    }//GEN-LAST:event_butt_lichchieuMouseEntered

    private void butt_lichchieuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butt_lichchieuMouseExited
       butt_lichchieu.setBackground(Color.WHITE);
    }//GEN-LAST:event_butt_lichchieuMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        Home newJFrame1 = new Home();

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel but_baocao;
    private javax.swing.JPanel but_datve_qlbv;
    private javax.swing.JPanel but_hoadon;
    private javax.swing.JPanel but_nhanvien;
    private javax.swing.JPanel but_phongchieu;
    private javax.swing.JPanel but_taikhoan;
    private javax.swing.JPanel but_tracuuve_qlbv;
    private javax.swing.JPanel butt_datve;
    private javax.swing.JPanel butt_lichchieu;
    private javax.swing.JPanel butt_loaiphim;
    private javax.swing.JPanel butt_phim;
    private javax.swing.JPanel butt_sanpham;
    private javax.swing.JPanel butt_thanhvien;
    private javax.swing.JPanel butt_themthanhvien;
    private javax.swing.JPanel butt_tracuuthanhvien;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel label_thanhvien;
    private javax.swing.JPanel panel_DatVe;
    private javax.swing.JPanel panel_baocao;
    private javax.swing.JPanel panel_center;
    private javax.swing.JPanel panel_hoadon;
    private javax.swing.JPanel panel_lichchieu;
    private javax.swing.JPanel panel_loaiphim;
    private javax.swing.JPanel panel_nhanvien;
    private javax.swing.JPanel panel_phim;
    private javax.swing.JPanel panel_phongchieu;
    private javax.swing.JPanel panel_sanpham;
    private javax.swing.JPanel panel_taikhoan;
    private javax.swing.JPanel panel_thanhvien;
    private javax.swing.JPanel panel_trangchu;
    // End of variables declaration//GEN-END:variables
}
